### ISSUE TITLE
VMware+Gazebo Z-ordering issue

### ISSUE THREAD

**Issue by bkinman** [udacity/RoboND-Perception-Exercises#4]
Getting this error with the older VM:
gzserver: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreRenderSystem.cpp:546: virtual void Ogre::RenderSystem::setDepthBufferFor(Ogre::RenderTarget*): Assertion `bAttached && "A new DepthBuffer for a RenderTarget was created, but after creation" "it says it's incompatible with that RT"' failed.

Not sure if it's happening with newer VM, will report findings.

This may not be a widespread problem, but there _is_ a ticket for it, it seems.

https://bitbucket.org/osrf/gazebo/issues/1837/vmware-rendering-z-ordering-appears-random

**Comment by hvpandya** [comment]
This is fixed in new VM. 

You can fix this in your VM too by forcing the VM to use OpenGL  2.1 instead of 3.x
```
$ echo "export SVGA_VGPU10=0" >> ~/.bashrc
```

**Comment by dbdxnuliba** [comment]
I also have this problem

**Comment by tftangming** [comment]
> I also have this problem
I want to know if you have solved the problem.If can,I hope you can help me fix the question.Thanks~
